# Generated by Django 2.2.17 on 2020-12-23 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20201223_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='ghfghfgh',
        ),
        migrations.AddField(
            model_name='customtext',
            name='hjghg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customtext_hjghg', to=settings.AUTH_USER_MODEL),
        ),
    ]
