# Generated by Django 2.2.17 on 2020-12-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201223_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hjghg',
        ),
    ]
