# Generated by Django 2.2.17 on 2020-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20201223_0657"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hgfhfghfgh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hjgjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgjhgjhg",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
